resolver: lts-7.18
compiler: ghc-8.0.2
compiler-check: match-exact
install-ghc: true

packages:
- .

extra-deps:
- thread-local-storage-0.1.0.4
- choice-0.2.0

nix:
  enable: true
  shell-file: shell.nix
