resolver: lts-7.14

packages:
- .
- jni
- jvm
- jvm-streaming
- location: vendor/inline-c
  extra-dep: true

extra-deps:
- thread-local-storage-0.1.0.3

skip-ghc-check: true

nix:
  # Requires Stack >= 1.2.
  shell-file: shell.nix

docker:
  enable: false
  image: tweag/inline-java
  stack-exe: image
