resolver: lts-8.18

packages:
- .
- jni
- jvm
- jvm-streaming
- examples/classpath

nix:
  # Requires Stack >= 1.2.
  shell-file: shell.nix

docker:
  enable: false
  image: tweag/inline-java
  stack-exe: image

explicit-setup-deps:
  classpath: true
