require-stack-version: ">= 1.2"

resolver: nightly-2017-12-01

packages:
- .
- jni
- jvm
- jvm-streaming
- examples/classpath

extra-deps:
- mmorph-1.0.9
- streaming-0.1.4.5

nix:
  shell-file: shell.nix
  path: ["nixpkgs=./nixpkgs.nix"]

docker:
  enable: false
  image: tweag/inline-java
  stack-exe: image
