require-stack-version: ">= 1.2"

resolver: lts-9.0

packages:
- .
- jni
- jvm
- jvm-streaming
- examples/classpath

nix:
  shell-file: shell.nix
  path: ["nixpkgs=./nixpkgs.nix"]

docker:
  enable: false
  image: tweag/inline-java
  stack-exe: image
