require-stack-version: ">= 1.5"

resolver: nightly-2017-08-15

compiler: ghc-8.2.1
allow-newer: true
skip-ghc-check: true

packages:
- .
- jni
- jvm
- jvm-streaming
- examples/classpath

nix:
  shell-file: shell.nix

docker:
  enable: false
  image: tweag/inline-java
  stack-exe: image
