resolver: lts-7.18
compiler: ghc-8.0.2
compiler-check: match-exact
require-stack-version: ">= 1.3.0 && < 1.4.0"
install-ghc: true

packages:
- .
- jni
- jvm
# - jvm-streaming

extra-deps:
- choice-0.2.0
- inline-c-0.5.6.1
- thread-local-storage-0.1.1

nix:
  enable: true
  shell-file: shell.nix

docker:
  enable: false
  image: tweag/inline-java
  stack-exe: image
