resolver: lts-7.18
compiler: ghc-8.0.2
compiler-check: match-exact
require-stack-version: ">= 1.3.0 && < 1.4.0"
install-ghc: true

packages:
- .
- ../jni

extra-deps:
- thread-local-storage-0.1.1
- choice-0.2.0

nix:
  enable: true
  shell-file: shell.nix
