version: 2
jobs:
  build:
    working_directory: ~/inline-java
    docker:
    - image: tweag/inline-java
    steps:
    - checkout
    - run:
        name: compute checksum
        command: |
          find . -path ./.git -prune -o -name "*.cabal" -print0 | sort -z | xargs -0 -n1 sha1sum > checksum.txt
          sha1sum stack.yaml >> checksum.txt
    - restore_cache:
        key: inline-java-stack-dependencies-{{ checksum "checksum.txt" }}
    - run:
        name: build dependencies
        command: stack --no-terminal build --only-dependencies --prefetch --test --bench
    - save_cache:
        key: inline-java-stack-dependencies-{{ checksum "checksum.txt" }}
        paths:
        - ~/.stack
    - run:
        name: build project
        command: stack --no-terminal build --pedantic --test --bench --no-run-tests --no-run-benchmarks
    - run:
        name: test
        command: stack --no-terminal test
